'use client';
import {useState} from 'react';
import type {Stream,SearchQuery,Topic,Language} from '../../lib/catalog.ts';
import type {Run} from '../../lib/store.ts';
export type Connection={configured:boolean;verified:boolean;total:number;shown:number;used:number;cooldownUntil:number};
export function ConnectionPanel({connection,runs,busy,onCollect,onReanalyze}:{connection:Connection;runs:Run[];busy:boolean;onCollect:()=>void;onReanalyze:()=>void}){
 return <div className="panel"><h2>Подключение Threads</h2><p>{!connection.configured?'Нет токена. До его добавления поиск не выполняется.':connection.verified?'Есть успешные ответы API. Полнота и география выдачи ещё не подтверждены.':'Токен добавлен; доступ к поиску ещё не проверен.'}</p><p>Токен задаётся в Railway → Variables → <code>THREADS_ACCESS_TOKEN</code>. Нужны права <code>threads_basic</code> и <code>threads_keyword_search</code>. Поиск запускается в скринере по выбранным языку и темам.</p><div className="actions"><button className="primary" disabled={busy||!connection.configured} onClick={onCollect}>{busy?'Выполняется…':'Открыть поиск'}</button><button className="secondary" disabled={busy||!connection.total} onClick={onReanalyze}>Пересчитать сохранённые публикации</button></div><p>Сохранено реальных публикаций: {connection.total}. В интерфейс загружается до 1000 последних. Запросов за 24 часа: {connection.used}. Внутренний суточный лимит отключён; ограничения Meta действуют. Планировщик не запущен.</p>{connection.cooldownUntil>Date.now()&&<p>Пауза после лимита до {new Date(connection.cooldownUntil).toLocaleString()}.</p>}<h2>Журнал запросов</h2>{!runs.length?<p>Реальных обращений ещё не было.</p>:<div className="table-wrap"><table><thead><tr><th>Запрос / время</th><th>Статус</th><th>Вызовы</th><th>Получено / новых / пропущено</th><th>Примечание</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{r.query_text}<br/><small>{new Date(r.started_at).toLocaleString()}</small></td><td>{r.status}</td><td>{r.requests}</td><td>{r.received} / {r.inserted} / {r.skipped}</td><td>{r.message}</td></tr>)}</tbody></table></div>}<p className="hint">Пустой ответ не доказывает отсутствие спроса. Статус partial означает неполную загрузку; данные не подменяются примерами.</p></div>;
}
export function QueryEditor({queries,busy,onSave}:{queries:SearchQuery[];busy:boolean;onSave:(queries:SearchQuery[])=>void}){
 const [draft]=useState(queries),[language,setLanguage]=useState('all'),[query,setQuery]=useState('');

 return <div className="panel"><h2>Поисковые формулировки</h2><p>{draft.length} подготовленных запросов. Это гипотезы поиска, не измеренная частотность. Скринер автоматически использует все формулировки выбранного языка и темы, включая широкие. Здесь можно изучить состав поиска. До двух страниц каждой формулировки; внутренний суточный лимит отключён. Ограничения Meta и пауза после их достижения сохраняются.</p><div className="screener-filters"><input aria-label="Найти запрос" placeholder="Фильтр запросов…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Язык запросов" value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">Все языки</option>{['ru','uk','en','es','und'].map(l=><option key={l}>{l}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Язык</th><th>Тема</th><th>Запрос</th><th>Тип</th></tr></thead><tbody>{draft.filter(q=>(language==='all'||q.language===language)&&q.text.toLowerCase().includes(query.toLowerCase())).map(q=><tr key={q.id}><td>{q.language}</td><td>{q.topicId}</td><td>{q.text}</td><td>{q.tier==='broad'?'Широкий / шумный':'Целевой'}</td></tr>)}</tbody></table></div></div>;
}
export function StreamEditor({streams,topics,busy,onSave}:{streams:Stream[];topics:Topic[];busy:boolean;onSave:(streams:Stream[])=>void}){
 const [draft,setDraft]=useState(streams);
 const update=(id:string,patch:Partial<Stream>)=>setDraft(d=>d.map(s=>s.id===id?{...s,...patch}:s));
 return <div className="panel"><h2>Потоки скринера</h2><p>Сохранённые фильтры одних и тех же публикаций. Потоки не меняют регион аккаунта Threads. Отрасль «Недвижимость» включает смежные ниши; все остальные публикации остаются в общем скринере.</p>{draft.map(s=><details key={s.id} className="stream-editor"><summary>{s.name}</summary><label>Название<input value={s.name} onChange={e=>update(s.id,{name:e.target.value})}/></label><div className="stream-options">{(['ru','uk','en','es','mixed','other'] as Language[]).map(l=><label key={l}><input type="checkbox" checked={s.languages.includes(l)} onChange={e=>update(s.id,{languages:e.target.checked?[...s.languages,l]:s.languages.filter(x=>x!==l)})}/>{l}</label>)}</div><p className="hint">Ни один язык не выбран = все определённые языки.</p><label><input type="checkbox" checked={s.includeUnknownLanguage} onChange={e=>update(s.id,{includeUnknownLanguage:e.target.checked})}/> Сохранять неизвестный язык</label><label>Отрасль<select value={s.industry} onChange={e=>update(s.id,{industry:e.target.value as 'any'|'property'})}><option value="property">Недвижимость и смежные</option><option value="any">Все отрасли</option></select></label><div className="stream-options">{topics.map(t=><label key={t.id}><input type="checkbox" checked={s.topicIds.includes(t.id)} onChange={e=>update(s.id,{topicIds:e.target.checked?[...s.topicIds,t.id]:s.topicIds.filter(x=>x!==t.id)})}/>{t.name}</label>)}</div><p className="hint">Ни одна тема не выбрана = все темы. География проекта сейчас неизвестна: исключения стран не настроены, неизвестные значения сохраняются.</p></details>)}<div className="actions"><button className="secondary" onClick={()=>setDraft(d=>[...d,{id:crypto.randomUUID(),name:'Новый поток',languages:[],topicIds:[],intentIds:[],industry:'any',includeUnknownLanguage:true,includeUnknownGeography:true,excludedProjectCountries:[]}])} disabled={draft.length>=30}>Добавить поток</button><button className="primary" disabled={busy} onClick={()=>onSave(draft)}>Сохранить потоки</button></div></div>;
}
