import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../lib/store.ts';
import {collect} from '../lib/collector.ts';
import {fetchPage,parsePage,safePermalink,ThreadsError} from '../lib/threads.ts';
import {defaults} from '../lib/catalog.ts';
const media={id:'100',text:'Нужна CRM для недвижимости',permalink:'https://www.threads.net/@sample/post/abc',timestamp:'2026-09-25T10:00:00Z'};
const fake=(body:unknown,status=200,headers?:Record<string,string>)=>(async()=>new Response(JSON.stringify(body),{status,headers})) as typeof fetch;
test('missing token makes no request',async()=>{const s=new Store(':memory:');let calls=0;try{await assert.rejects(()=>collect(s,'',undefined,(async()=>{calls++;throw Error();}) as typeof fetch),/токен/);assert.equal(calls,0);assert.equal(s.runs().length,0);}finally{s.close();}});
test('overlapping queries and repeated collection do not duplicate posts',async()=>{const s=new Store(':memory:');try{await collect(s,'dummy-token',undefined,fake({data:[media]}));assert.equal(s.count(),1);assert.equal(s.runs().length,2);assert.equal(s.runs().reduce((n,r)=>n+r.inserted,0),1);s.feedback('100','useful');await collect(s,'dummy-token',undefined,fake({data:[media]}));assert.equal(s.count(),1);assert.equal(s.feedbackMap().get('100'),'useful');s.reanalyze(defaults);assert.equal(s.feedbackMap().get('100'),'useful');}finally{s.close();}});
test('pagination truncation does not advance checkpoint',async()=>{const s=new Store(':memory:');try{await collect(s,'dummy',['crm-ru-0'],fake({data:[media],paging:{next:'https://evil.invalid/?access_token=secret',cursors:{after:'cursor1'}}}));assert.equal(s.runs()[0].status,'partial');assert.equal(s.checkpoint('crm-ru-0','нужна CRM'),undefined);assert.equal(s.count(),1);}finally{s.close();}});
test('API next URL is never followed; cursor uses fixed Meta endpoint',async()=>{const urls:string[]=[];const f=(async(url:URL|string)=>{urls.push(String(url));return new Response(JSON.stringify(urls.length===1?{data:[media],paging:{next:'https://evil.invalid/',cursors:{after:'safe-cursor'}}}:{data:[]}));}) as typeof fetch;const s=new Store(':memory:');try{await collect(s,'secret',['crm-ru-0'],f);assert.equal(urls.length,2);assert.ok(urls.every(u=>new URL(u).hostname==='graph.threads.net'));assert.equal(new URL(urls[1]).searchParams.get('after'),'safe-cursor');assert.equal(s.runs()[0].status,'complete');}finally{s.close();}});
test('rate limit establishes cooldown and stores no raw token errors',async()=>{const s=new Store(':memory:');try{await assert.rejects(()=>collect(s,'SECRET',['crm-ru-0'],fake({error:{code:4,message:'SECRET'}},429,{'retry-after':'120'})),/Лимит API/);assert.ok(s.get<number>('cooldownUntil',0)>Date.now());assert.ok(!JSON.stringify(s.runs()).includes('SECRET'));assert.equal(s.runs()[0].status,'error');await assert.rejects(()=>collect(s,'SECRET',['crm-ru-0'],fake({data:[]})),/паузы/);}finally{s.close();}});
test('permission errors are actionable and token-free',async()=>{await assert.rejects(()=>fetchPage({token:'SECRET',query:'CRM',since:'2026-09-24',until:'2026-09-25',fetcher:fake({error:{code:10,message:'SECRET'}},403)}),(e:unknown)=>e instanceof ThreadsError&&e.code==='permission'&&!e.message.includes('SECRET'));});
test('invalid records and unsafe links are isolated',()=>{const p=parsePage({data:[media,{...media,id:'2',permalink:'javascript:alert(1)'},{id:'3'},null]});assert.equal(p.media.length,2);assert.equal(p.skipped,2);assert.equal(p.media[1].permalink,null);assert.equal(safePermalink('https://threads.net.evil.com/a'),null);assert.equal(safePermalink('https://user:password@threads.net/a'),null);assert.throws(()=>parsePage({error:{}}));});
test('concurrent collectors use a shared database lease',async()=>{const s=new Store(':memory:');try{const lease=s.acquire();assert.ok(lease);await assert.rejects(()=>collect(s,'dummy',undefined,fake({data:[]})),/уже выполняется/);s.release(lease!);assert.ok(s.acquire());}finally{s.close();}});
test('collection continues beyond 100 calls without resetting usage history',async()=>{const s=new Store(':memory:');try{const id=s.startRun('q','CRM','2026-09-24','2026-09-25');for(let i=0;i<100;i++)s.recordRequest(id);s.finishRun(id,'complete','');let calls=0;const result=await collect(s,'dummy',['crm-ru-0'],(async()=>{calls++;return new Response(JSON.stringify({data:[media]}));}) as typeof fetch);assert.equal(calls,1);assert.equal(result.inserted,1);assert.equal(s.requestCount(),101);}finally{s.close();}});
test('credentials stay in authorization header, never in URL',async()=>{let called=false;await fetchPage({token:'SECRET',query:'CRM',since:'2026-09-24',until:'2026-09-25',fetcher:(async(url:URL|string,init:RequestInit)=>{called=true;assert.ok(!String(url).includes('SECRET'));assert.equal((init.headers as Record<string,string>).Authorization,'Bearer SECRET');return new Response('{"data":[]}');}) as typeof fetch});assert.ok(called);});
test('completed run advances watermark; repeat uses overlap and preserves first seen',async()=>{const s=new Store(':memory:');try{await collect(s,'dummy',['crm-ru-0'],fake({data:[media]}));const checkpoint=s.checkpoint('crm-ru-0','нужна CRM')!;const first=s.rows()[0].first_seen_at;let since='';await collect(s,'dummy',['crm-ru-0'],(async(url:URL|string)=>{since=new URL(String(url)).searchParams.get('since')!;return new Response(JSON.stringify({data:[media]}));}) as typeof fetch);assert.equal(Number(since),Math.floor((Date.parse(checkpoint)-600000)/1000));assert.equal(s.rows()[0].first_seen_at,first);}finally{s.close();}});

test('collects more than three selected queries sequentially and deduplicates posts',async()=>{
 const store=new Store(':memory:');let calls=0;
 store.set('queries',Array.from({length:5},(_,i)=>({id:'q'+i,topicId:'crm',language:'ru',text:'CRM '+i,tier:'focused',enabled:true})));
 const result=await collect(store,'test-token',undefined,async()=>{calls++;return new Response(JSON.stringify({data:[media]}));});
 assert.equal(calls,5);assert.equal(result.requests,5);assert.equal(result.received,5);assert.equal(result.inserted,1);assert.equal(result.partial,0);store.close();
});
