'use client';
import {useEffect,useState,useRef} from 'react';
import {analyze,fragments,labels,type Topic,type Post} from '../lib/radar.ts';
import {streamExclusions} from '../lib/analysis.ts';
import type {Stream,SearchQuery} from '../lib/catalog.ts';
import type {Run} from '../lib/store.ts';
import {ConnectionPanel,QueryEditor,StreamEditor,type Connection} from './components/Setup';
export default function Home(){
 const [source,setSource]=useState('threads'),[streamId,setStreamId]=useState('all'),[streams,setStreams]=useState<Stream[]>([]),[queries,setQueries]=useState<SearchQuery[]>([]),[runs,setRuns]=useState<Run[]>([]),[connection,setConnection]=useState<Connection>({configured:false,verified:false,total:0,shown:0,budget:100,used:0,cooldownUntil:0});
 const [posts,setPosts]=useState<Post[]>([]),[topics,setTopics]=useState<Topic[]>([]),[draft,setDraft]=useState<Topic[]>([]);
 const [tab,setTab]=useState('feed'),[filter,setFilter]=useState('all'),[language,setLanguage]=useState('all'),[query,setQuery]=useState(''),[unread,setUnread]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[notice,setNotice]=useState('');
 const [searchLanguage,setSearchLanguage]=useState('ru'),[searchTopic,setSearchTopic]=useState('all'),[settingsTab,setSettingsTab]=useState('topics'),[progress,setProgress]=useState('');
 const stopSearch=useRef(false);
 const plan=queries.filter(q=>(q.language===searchLanguage||(q.language==='und'&&(!/[а-яё]/i.test(q.text)||['ru','uk'].includes(searchLanguage))))&&(searchTopic==='all'||q.topicId===searchTopic));
 async function searchNow(){
  if(busy)return;
  stopSearch.current=false;setBusy(true);setError('');setNotice('');setStreamId('all');setFilter('all');setQuery('');setUnread(false);setLanguage(searchLanguage);
  let done=0,inserted=0,received=0,partial=0;
  try{
   for(const q of plan){
    if(stopSearch.current)break;
    setProgress(`Проверено ${done} из ${plan.length} · новых ${inserted} · ищем «${q.text}»`);
    const response=await fetch('/api/collect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({queryId:q.id})});
    const data=await response.json();if(!response.ok)throw Error(data.error||'Ошибка поиска');
    done++;inserted+=data.inserted;received+=data.received;partial+=data.partial;
    await refresh();
   }
   setNotice(`${stopSearch.current?'Поиск остановлен':'Поиск завершён'}: ${done}/${plan.length} формулировок · новых уникальных публикаций: ${inserted}.${partial?' Неполных выдач: '+partial+'. См. журнал.':''}`);
  }catch(e){setError(`${String(e)} Завершено ${done}/${plan.length}; уже полученные публикации сохранены.`);try{await refresh();}catch{}}
  finally{setProgress('');setBusy(false);}
 }
 function apply(data:{posts:Post[],topics:Topic[],streams:Stream[],queries:SearchQuery[],runs:Run[],connection:Connection}){setPosts(data.posts);setTopics(data.topics);setDraft(data.topics);setStreams(data.streams);setQueries(data.queries);setRuns(data.runs);setConnection(data.connection);setLoaded(true);}
 useEffect(()=>{const controller=new AbortController();setLoaded(false);setPosts([]);fetch('/api/radar?source='+source,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Не удалось загрузить базу');return r.json();}).then(apply).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[source]);
 async function refresh(){const r=await fetch('/api/radar?source='+source);if(!r.ok)throw Error('Ошибка чтения базы');apply(await r.json());}
 async function save(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,source})});const data=await r.json();if(!r.ok)throw Error(data.error);apply(data);setNotice('Сохранено');}catch(e){setError(String(e));}finally{setBusy(false);}}
 const assessed=posts.map(p=>({...p,result:analyze(p.text,topics)}));
 const currentStream=streams.find(s=>s.id===streamId);
 const streamPosts=assessed.filter(p=>!currentStream||!streamExclusions(p.result,currentStream,p.language,p.projectCountry??null).length);
 const visible=streamPosts.filter(p=>(filter==='all'||p.result.category===filter)&&(language==='all'||p.language===language||p.language==='und'||p.language==='mixed')&&(!unread||!p.feedback)&&p.text.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>b.result.score-a.result.score);
 const matched=assessed.filter(p=>p.result.topics.length).length, high=assessed.filter(p=>p.result.priority==='high').length, useful=posts.filter(p=>p.feedback==='useful').length;
 function edit(i:number,patch:Partial<Topic>){setDraft(d=>d.map((t,n)=>n===i?{...t,...patch}:t));}
 return <div className="screener-shell"><div className="screener-top"><strong>Intent Radar</strong><nav>{[['feed','Скринер'],['streams','Потоки'],['research','Исследование'],['settings','Настройки'],['connection','Подключение']].map(([id,title])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{title}</button>)}</nav><span>Threads · {connection.verified?'API отвечал':connection.configured?'доступ не проверен':'нет токена'}</span></div><main><section className="content">
 <div className="demo-strip">{source==='demo'?'DEMO · Вымышленные публикации':'THREADS · Сохранённые результаты API'} · {posts.length} строк · {matched} совпадений · {high} запросов исполнителя</div>
 {error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 {tab==='settings'&&<nav className="screener-filters"><button onClick={()=>setSettingsTab('topics')}>Словарь тем</button><button onClick={()=>setSettingsTab('queries')}>Поисковые формулировки</button></nav>}
 {tab==='feed'&&<><div className="search-controls"><label>Язык поиска <select disabled={busy} value={searchLanguage} onChange={e=>setSearchLanguage(e.target.value)}>{[['ru','Русский'],['uk','Українська'],['en','English'],['es','Español']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Темы <select disabled={busy} value={searchTopic} onChange={e=>setSearchTopic(e.target.value)}><option value="all">Все темы</option>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="primary" disabled={busy||!loaded||!connection.configured||!plan.length} onClick={searchNow}>Найти публикации</button>{busy&&progress&&<button onClick={()=>{stopSearch.current=true;setProgress(p=>p+' · остановка после текущего запроса');}}>Остановить</button>}<span>{plan.length} формулировок · последние 24 часа при первом поиске</span></div><p className="hint">Язык задаёт формулировки поиска. Результаты фильтруются у нас; смешанный и неопределённый язык сохраняются. Повторный поиск собирает новые посты с перекрытием 10 минут. Держите вкладку открытой до завершения. Бюджет: {connection.used}/{connection.budget} обращений за 24 часа.</p>{progress&&<div role="status" className="notice">{progress}</div>}<p className="hint">Ниже — фильтры сохранённых публикаций. Они не запускают поиск.</p><div className="screener-filters"><select aria-label="Поток" value={streamId} onChange={e=>setStreamId(e.target.value)}><option value="all">Все потоки</option>{streams.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input aria-label="Поиск по тексту" placeholder="Найти в тексте…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Тип намерения" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все намерения</option>{Object.entries(labels).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select><select aria-label="Язык" value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">Все языки</option><option value="ru">Русский</option><option value="uk">Українська</option><option value="en">English</option><option value="es">Español</option><option value="mixed">Смешанный</option><option value="other">Другой</option><option value="und">Не определён</option></select><label><input type="checkbox" checked={unread} onChange={e=>setUnread(e.target.checked)}/> Без оценки</label><span>{visible.length} строк</span></div>
 <div className="screen-table"><div className="screen-head"><span>Тема</span><span>Язык</span><span>Текст публикации · нажмите для подробностей</span><span>Намерение</span><span>Ссылка</span></div>{!loaded&&!error&&<p className="empty">Загружаем…</p>}{loaded&&!visible.length&&<p className="empty">{source==='demo'?'Нет демопримеров по выбранным фильтрам. Сейчас примеры только RU/UK.':'Нет реальных публикаций по этим фильтрам. Выберите язык и темы выше и нажмите «Найти публикации». Попробуйте также все языки в фильтре сохранённых результатов.'}</p>}{visible.map(p=><div className="signal-line" key={p.id}><details><summary className={'screen-row '+p.result.priority}><span className="row-topic" title={p.result.topics.join(', ')}>{p.result.topics.map(t=>t==='CRM и автоматизация'?'CRM':t==='Реклама и маркетинг'?'Маркетинг':t).join(', ')||'—'}</span><span className="row-language">{p.language.toUpperCase()}</span><span className="row-preview">{fragments(p.text,[...p.result.words,p.result.evidence]).map((f,i)=>f.hit?<mark key={i}>{f.text}</mark>:<span key={i}>{f.text}</span>)}</span><span className={'row-intent '+p.result.priority}>{labels[p.result.category]}</span></summary><div className="row-detail"><p className="post-text">{fragments(p.text,[...p.result.words,p.result.evidence]).map((f,i)=>f.hit?<mark key={i}>{f.text}</mark>:<span key={i}>{f.text}</span>)}</p><p className="detail-reason">Совпадения: {p.result.words.join(', ')||'нет'}{p.result.evidence?' · Сигнал: «'+p.result.evidence+'»':''} · Отрасль: {p.result.industry==='property'?'недвижимость':p.result.industry==='adjacent'?'смежная':'не определена'}{p.result.industryEvidence?' («'+p.result.industryEvidence+'»)':''} · География: неизвестна · {source==='demo'?'язык примера задан вручную':'язык: эвристика, уверенность '+p.result.language.confidence} · {labels[p.result.category]}{p.firstSeenAt?' · Обнаружено: '+new Date(p.firstSeenAt).toLocaleString():''}</p><div className="feedback">{[['useful','Полезно'],['skip','Мимо'],['replied','Ответил']].map(([value,title])=><button disabled={busy} key={value} className={p.feedback===value?'chosen':''} onClick={()=>save({type:'feedback',id:p.id,value:p.feedback===value?'':value})}>{title}</button>)}</div></div></details><span className="row-link">{p.permalink?<a href={p.permalink} target="_blank" rel="noreferrer">Threads ↗</a>:<span title={source==='demo'?'Вымышленный пример без реальной ссылки':'API не вернул допустимую ссылку'}>{source==='demo'?'DEMO':'—'}</span>}</span></div>)}</div><p className="hint">Язык и страна — разные признаки. География пока неизвестна; фильтрации по странам нет. Недвижимость и смежные ниши повышают приоритет по явным словам. Языковые и смысловые правила приблизительны; их качество ещё не измерено на реальных публикациях.</p></>}
 {tab==='connection'&&<ConnectionPanel connection={connection} runs={runs} busy={busy} onCollect={()=>setTab('feed')} onReanalyze={()=>save({type:'reanalyze'})}/>}
 {tab==='settings'&&settingsTab==='queries'&&loaded&&<QueryEditor key={JSON.stringify(queries)} queries={queries} busy={busy} onSave={queries=>save({type:'queries',queries})}/>}
 {tab==='streams'&&loaded&&<StreamEditor key={JSON.stringify(streams)} streams={streams} topics={topics} busy={busy} onSave={streams=>save({type:'streams',streams})}/>}
 {tab==='settings'&&settingsTab==='topics'&&<div className="panel"><h2>Словарь наблюдения</h2><p>Ключевые слова разделяются запятыми. Сейчас совпадения ищутся по части слова; это прозрачный базовый алгоритм, который будем проверять на реальных данных.</p>{draft.map((t,i)=><div className="topic-row" key={t.id}><label className="topic-switch"><input type="checkbox" checked={t.enabled} onChange={e=>edit(i,{enabled:e.target.checked})}/> Включена</label><label>Название<input value={t.name} onChange={e=>edit(i,{name:e.target.value})}/></label><label>Ключевые слова<input value={t.words.join(',')} onChange={e=>edit(i,{words:e.target.value.split(',')})}/></label></div>)}<div className="actions"><button className="secondary" disabled={draft.length>=30} onClick={()=>setDraft(d=>[...d,{id:crypto.randomUUID(),name:'Новая тема',words:['пример'],enabled:true}])}>+ Добавить тему</button><button className="primary" disabled={busy||!loaded} onClick={()=>save({type:'topics',topics:draft.map(t=>({...t,name:t.name.trim(),words:[...new Set(t.words.map(w=>w.trim()).filter(Boolean))]}))})}>{busy?'Сохраняем…':'Сохранить и пересчитать'}</button></div><p className="hint">Изменение словаря пересчитывает сохранённые публикации. Ручные отметки сохраняются независимо от правил.</p></div>}
 {tab==='research'&&<div className="panel"><h2>Что проходит через фильтр</h2><p>Текущий источник: {source==='demo'?'демопримеры':'реальные публикации'}. Получено в экран: {posts.length}; после потока: {streamPosts.length}; после фильтров: {visible.length}. Это сводка выборки, не оценка объёма всего Threads. Классификатор использует правила.</p><div className="table-wrap"><table><thead><tr><th>Тема</th><th>Совпадения</th><th>Исполнитель</th><th>Полезно</th></tr></thead><tbody>{topics.map(t=>{const group=assessed.filter(p=>p.result.topics.includes(t.name));return <tr key={t.id}><td>{t.name}{!t.enabled?' · выключена':''}</td><td>{group.length}</td><td>{group.filter(p=>p.result.category==='contractor').length}</td><td>{group.filter(p=>p.feedback==='useful').length}</td></tr>;})}</tbody></table></div><p className="hint">Одна публикация может относиться к нескольким темам. Суммы по темам могут превышать количество уникальных публикаций.</p><h2>Следующий эксперимент</h2><ol><li>Подключить приложение Meta и подтвердить доступ к поиску.</li><li>Проверить выдачу на русском и украинском, доступную историю и квоты.</li><li>Собрать реальную выборку и разметить намерение автора.</li><li>Сравнить правила и смысловой анализ на отложенной части выборки.</li></ol><div className="research-status">{connection.verified?'API отвечал · проверяем качество выдачи':'Доступ к API ещё не проверен'}</div></div>}
 <div className="bottom-note">RESET · INTENT RADAR <span>{source==='demo'?'Демо':'Threads'} · Правила v0.2</span></div></section></main></div>;
}
