export type Language = 'ru'|'uk'|'en'|'es'|'mixed'|'other'|'und';
export type Topic = {id:string; name:string; words:string[]; enabled:boolean};
export type SearchQuery = {id:string; topicId:string; language:Language; text:string; tier:'focused'|'broad'; enabled:boolean};
export type Stream = {id:string; name:string; languages:Language[]; topicIds:string[]; intentIds:string[]; includeUnknownLanguage:boolean; industry:'any'|'property'; excludedProjectCountries:string[]; includeUnknownGeography:boolean};
export const catalog = [
 {id:'crm',name:'CRM',terms:{ru:['crm','срм','црм','учёт клиентов','учет клиентов'],uk:['crm','срм','облік клієнтів'],en:['crm','customer management'],es:['crm','gestión de clientes','gestion de clientes']},queries:{ru:['нужна CRM','CRM для недвижимости','внедрение CRM'],uk:['потрібна CRM','CRM для нерухомості','впровадження CRM'],en:['need a CRM','real estate CRM','CRM implementation'],es:['necesito un CRM','CRM inmobiliario','implementar CRM']}},
 {id:'web',name:'Сайты и лендинги',terms:{ru:['сайт','лендинг','лендос'],uk:['сайт','лендінг'],en:['website','landing page','web design'],es:['página web','pagina web','sitio web','landing page']},queries:{ru:['нужен сайт','сайт агентства недвижимости','ищу веб разработчика'],uk:['потрібен сайт','сайт нерухомості','шукаю розробника'],en:['need a website','real estate website','looking for web developer'],es:['necesito una web','web inmobiliaria','busco desarrollador web']}},
 {id:'ads',name:'Реклама и маркетинг',terms:{ru:['реклам','маркетинг','таргет','smm','seo','лидогенерац','заявки','заявок'],uk:['реклам','маркетинг','таргет','лідогенерац','ліди'],en:['marketing','advertising','facebook ads','instagram ads','lead generation','google ads','seo'],es:['publicidad','marketing','captación','captacion','anuncios','leads','seo']},queries:{ru:['ищу таргетолога','маркетинг недвижимости','нет заявок'],uk:['шукаю таргетолога','реклама нерухомості','немає заявок'],en:['looking for a marketer','real estate marketing','need more leads'],es:['busco experto publicidad','marketing inmobiliario','necesito leads']}},
 {id:'database',name:'Базы данных',terms:{ru:['базу данных','база данных','базы данных','каталог объектов','базу объектов'],uk:['база даних','базу даних','бази даних','каталог об’єктів'],en:['database','property database','data migration'],es:['base de datos','bases de datos','migración de datos']},queries:{ru:['нужна база данных','база объектов недвижимости','разработка базы данных'],uk:['потрібна база даних','база об’єктів нерухомості','розробка бази даних'],en:['need a database','property database','database developer'],es:['necesito base de datos','base de datos inmobiliaria','desarrollador base de datos']}},
 {id:'automation',name:'Автоматизация и интеграции',terms:{ru:['автоматизац','интеграц','бот','n8n','make.com','zapier'],uk:['автоматизац','інтеграц','бот'],en:['automation','automate','integration','workflow','chatbot','n8n','zapier'],es:['automatiz','integración','integracion','chatbot']},queries:{ru:['нужна автоматизация','интеграция CRM','автоматизация агентства'],uk:['потрібна автоматизація','інтеграція CRM','автоматизація агенції'],en:['need automation','CRM integration','automate real estate'],es:['necesito automatizar','integración CRM','automatización inmobiliaria']}},
 {id:'development',name:'Заказная разработка',terms:{ru:['разработчик','разработчика','разработку','приложение','личный кабинет','портал','программист'],uk:['розробник','розробника','розробку','додаток','кабінет'],en:['developer','custom software','application','software development'],es:['desarrollador','desarrollo','software a medida','aplicación','aplicacion']},queries:{ru:['ищу разработчика','заказная разработка','портал недвижимости'],uk:['шукаю програміста','замовна розробка','портал нерухомості'],en:['looking for a developer','custom software real estate','need custom software'],es:['busco desarrollador','software inmobiliario','necesito software a medida']}}
] as const;
export const defaults:Topic[]=catalog.map(t=>({id:t.id,name:t.name,enabled:true,words:[...new Set(Object.values(t.terms).flat())]}));
export const searchQueries:SearchQuery[]=catalog.flatMap(t=>Object.entries(t.queries).flatMap(([language,qs])=>qs.map((text:string,i:number)=>({id:`${t.id}-${language}-${i}`,topicId:t.id,language:language as Language,text,tier:'focused' as const,enabled:t.id==='crm'&&['ru','uk'].includes(language)&&i===0}))));
export const broadQueries:SearchQuery[]=['CRM','Facebook','Instagram','Meta','маркетинг','marketing'].map((text,i)=>({id:`broad-${i}`,topicId:i===0?'crm':'ads',language:'und',text,tier:'broad',enabled:false}));
export const allQueries=[...searchQueries,...broadQueries];
export const defaultStreams:Stream[]=[
 {id:'property-ru-uk',name:'Недвижимость · RU/UK',languages:['ru','uk','mixed'],topicIds:[],intentIds:[],includeUnknownLanguage:true,industry:'property',excludedProjectCountries:[],includeUnknownGeography:true},
 {id:'property-en',name:'Real estate · EN',languages:['en'],topicIds:[],intentIds:[],includeUnknownLanguage:true,industry:'property',excludedProjectCountries:[],includeUnknownGeography:true},
 {id:'property-es',name:'Inmobiliario · ES',languages:['es'],topicIds:[],intentIds:[],includeUnknownLanguage:true,industry:'property',excludedProjectCountries:[],includeUnknownGeography:true},
 {id:'software',name:'CRM / данные / разработка · все ниши',languages:[],topicIds:['crm','database','automation','development'],intentIds:[],includeUnknownLanguage:true,industry:'any',excludedProjectCountries:[],includeUnknownGeography:true}
];
